### ISSUE TITLE
panic when opening stream

### ISSUE THREAD

**Issue by 33560303** [rzeldent/esp32cam-rtsp#154]
I have added a new board to this software. It is not stable so I did not do a pull request yet.
The board is functional (wifi works, I can log in and see the status). However when I open a new stream (or snapshot), the kernel panics.
Does somebody know where to look for an improvement? I have been looking into the pointer to the camera object but nothing seems wrong.
I am using the development branch

**Logging from boot to panic here, board configuration file below:**
```

16:37:56.867 > Rebooting...
16:37:57.143 > ESP-ROM:esp32s3-20210327
16:37:57.143 > Build:Mar 27 2021
16:37:57.143 > rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
16:37:57.143 > Saved PC:0x420a2a22
  #0  0x420a2a22 in esp_pm_impl_waiti at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_pm/pm_impl.c:855

16:37:57.143 > SPIWP:0xee
16:37:57.143 > mode:DIO, clock div:1
16:37:57.143 > load:0x3fce3808,len:0x4bc
16:37:57.143 > load:0x403c9700,len:0xbd8
16:37:57.143 > load:0x403cc700,len:0x2a0c
16:37:57.143 > entry 0x403c98d0
16:37:57.143 > [   196][V][WiFiServer.h:42] WiFiServer(): WiFiServer::WiFiServer(port=80, ...)
16:37:57.143 > [   203][V][WebServer.cpp:88] WebServer(): WebServer::Webserver(port=80)
16:37:57.143 > [   229][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
16:38:02.122 > [  5253][I][main.cpp:332] setup(): Core debug level: 5
16:38:02.123 > [  5254][I][main.cpp:333] setup(): CPU Freq: 240 Mhz, 2 core(s)
16:38:02.124 > [  5255][I][main.cpp:334] setup(): Free heap: 292980 bytes
16:38:02.124 > [  5255][I][main.cpp:335] setup(): SDK version: v4.4.7-dirty
16:38:02.125 > [  5256][I][main.cpp:336] setup(): Board: esp32cam_goouuu
16:38:02.125 > [  5256][I][main.cpp:337] setup(): Starting ESP32CAM-RTSP...
16:38:02.126 > Config version: 1.6
16:38:02.126 > Config size: 333
16:38:02.128 > Loading configurations
16:38:02.128 > [iwcAll]
16:38:02.128 > |-- [iwcSys]
16:38:02.128 > |   |-- 'iwcThingName' with value: 'ESP32CAM-RTSP'
16:38:02.128 > |   |-- 'iwcApPassword' with value: <hidden>
16:38:02.128 > |   |-- [iwcWifi0]
16:38:02.128 > |   |   |-- 'iwcWifiSsid' with value: <redacted>
16:38:02.128 > |   |   \-- 'iwcWifiPassword' with value: <hidden>
16:38:02.129 > |   \-- 'iwcApTimeout' with value: '30'
16:38:02.129 > |-- [iwcCustom]
16:38:02.129 > |   \-- [camera]
16:38:02.129 > |       |-- 'fd' with value: '200'
16:38:02.129 > |       |-- 'fs' with value: 'VGA (640x480)'
16:38:02.129 > |       |-- 'q' with value: '14'
16:38:02.129 > |       |-- 'b' with value: '0'
16:38:02.130 > |       |-- 'c' with value: '0'
16:38:02.130 > |       |-- 's' with value: '0'
16:38:02.130 > |       |-- 'e' with value: 'Normal'
16:38:02.130 > |       |-- 'wb' with value: '1'
16:38:02.130 > |       |-- 'awbg' with value: '1'
16:38:02.130 > |       |-- 'wbm' with value: 'Auto'
16:38:02.130 > |       |-- 'ec' with value: '1'
16:38:02.131 > |       |-- 'aec2' with value: '1'
16:38:02.131 > |       |-- 'ael' with value: '0'
16:38:02.131 > |       |-- 'aecv' with value: '300'
16:38:02.131 > |       |-- 'gc' with value: '1'
16:38:02.131 > |       |-- 'agcg' with value: '0'
16:38:02.131 > |       |-- 'gcl' with value: '2X'
16:38:02.132 > |       |-- 'bpc' with value: '0'
16:38:02.132 > |       |-- 'wpc' with value: '1'
16:38:02.132 > |       |-- 'rg' with value: '1'
16:38:02.132 > |       |-- 'lenc' with value: '1'
16:38:02.132 > |       |-- 'hm' with value: '0'
16:38:02.132 > |       |-- 'vm' with value: '0'
16:38:02.133 > |       |-- 'dcw' with value: '1'
16:38:02.133 > |       \-- 'cb' with value: '0'
16:38:02.133 > \-- [hidden]
16:38:02.133 > [  5264][V][main.cpp:214] initialize_camera(): initialize_camera
16:38:02.134 > [  5265][I][main.cpp:216] initialize_camera(): Frame size: VGA (640x480)
16:38:02.134 > [  5266][I][main.cpp:218] initialize_camera(): JPEG quality: 14
16:38:02.135 > [  5266][I][main.cpp:220] initialize_camera(): Frame duration: 200 ms
16:38:02.337 > State changing from: 0 to 2
16:38:02.352 > [  5482][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 0 - WIFI_READY
16:38:02.388 > Setting up AP: ESP32CAM-RTSP
16:38:02.389 > Use password: <hidden>
16:38:02.389 > [  5520][V][WiFiGenic.cpp:393] _arduinoAPtarted
16:38:02.390 > [  5521][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 10 - AP_START
16:38:02.772 > AP IP address: 192.168.4.1
16:38:02.773 > [  5904][V][WiFiGeneric396] _arduinvet_b(APStopped
_eventCallback(): Arduino Event: 11 - AP_STOP]p[pW:1Fipp:393] _ardo4_event)0: ]A P Started
16:38:02.775 > [  5906][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 10 - AP_START
16:38:02.777 > AP timeout (ms): 30000
16:38:02.777 > State changed from: 0 to 2
16:38:32.778 > State changing from: 2 to 3
16:38:32.791 > 22][V][WiF.c:396] _ardu_een_c: P topped
16:38:32.792 > [ 35923][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 11 - AP_STOP
16:38:32.810 > Connecting to <redacted> (password is hidden)
16:38:32.811 > WiFi timeout (ms): 30000
16:38:32.824 > [ 35955][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 0 - WIFI_READY
a6:38:32.830 > neri[c 35.9c61]p[V]p[:W3iFi4G1e] _naerricd.ucivpent:_9c7b:]  setST_Aesp _Sittneterfd
16:38:32.831 > ce_[ 35962][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 2 - STA_START
16:38:32.832 > ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
16:38:32.838 > State changed from: 2 to 3
16:38:33.445 > [576][ViGcb(): STA connD:146BSSID: f8:0d:a9:2cc:c3, Rean:2
16:38:33.446 > [ 36577][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 5 - STA_DISCONNECTED
16:38:33.447 > [ 36578][W][WiFiGeneric.cpp:1062] _eventCallback(): Reason: 202 - AUTH_FAIL
16:38:33.448 > [ 36579][D][WiFiGeneric.cpp:1082] _eventCallback(): WiFi Reconnect Running
16:38:33.460 > [ 36591][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
16:38:37.904 > [V][WiFc3] _ard STA DSSID: 500c3, Reas[ 41036][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 5 - STA_DISCONNECTED
16:38:37.906 > [ 41037][W][WiFiGeneric.cpp:1062] _eventCallback(): Reason: 2 - AUTH_EXPIRE
16:38:37.907 > [ 41038][D][WiFiGeneric.cpp:1086] _eventCallback(): WiFi AutoReconnect Running
16:38:37.909 > [ 41040][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
16:38:38.986 > FiGpp:356ui_enected: S, BSSID3: WPA2_WPA[ 42118][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
16:38:39.087 > 2218][V][WiFric.cpt_cb():ot New92.1687
16:38:39.087 > [ 42218][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
16:38:39.088 > [ 42219][D][WiFiGeneric.cpp:1103] _eventCallback(): STA IP: 192.168.1.167, MASK: 255.255.255.0, GW: 192.168.1.1
16:38:39.089 > WiFi connected
16:38:39.089 > IP address: 192.168.1.167
16:38:39.089 > State changing from: 3 to 4
16:38:42.191 > [ 45322][W][ESPmDNS.cpp:222] queryService(): No results found!
16:38:42.191 > Active mDNS services: 0 
16:38:42.192 > Accepting connection
16:38:42.192 > [ 45323][V][main.cpp:300] on_connected(): on_connected
16:38:42.193 > [ 45324][V][main.cpp:291] start_rtsp_server(): start_rtsp_server
16:38:42.194 > [ 45325][V][WiFiServer.h:42] WiFiServer(): WiFiServer::WiFiServer(port=554, ...)
16:38:42.194 > [ 45326][I][rtsp_server.cpp:9] rtsp_server(): Starting RTSP server
16:38:42.205 > State changed from: 3 to 4
16:39:45.597 > Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
16:39:45.597 > 
16:39:45.597 > Core  1 register dump:
16:39:45.597 > PC      : 0x42014c63  PS      : 0x00060530  A0      : 0x8208ae40  A1      : 0x3fcebe40  
16:39:45.608 > A2      : 0x00000000  A3      : 0x3fcb16ec  A4      : 0x00000000  A5      : 0x00000008  
16:39:45.619 > A6      : 0x00000000  A7      : 0x3fc9d49c  A8      : 0x82014c60  A9      : 0x3fcebe20  
16:39:45.619 > A10     : 0x3fcaddac  A11     : 0x3fcb159c  A12     : 0x3fcaa7b8  A13     : 0x00000001  
16:39:45.630 > A14     : 0x00001800  A15     : 0x00004003  SAR     : 0x0000001a  EXCCAUSE: 0x0000001c  
16:39:45.641 > EXCVADDR: 0x00000008  LBEG    : 0x40056f5c  LEND    : 0x40056f72  LCOUNT  : 0xffffffff  
16:39:45.652 > 
16:39:45.652 > 
16:39:45.652 > Backtrace: 0x42014c60:0x3fcebe40 0x4208ae3d:0x3fcebe60 0x42014f9f:0x3fcebe80 0x420150ef:0x3fcebec0 0x42014d49:0x3fcebf10 0x42014d7c:0x3fcebf30 0x42006792:0x3fcebf50 0x42017ee1:0x3fcebf70
  #0  0x42014c60 in OV2640::getWidth() at .pio/libdeps/esp32cam_goouuu/Micro-RTSP/src/OV2640.cpp:125
  #1  0x4208ae3d in OV2640Streamer::OV2640Streamer(WiFiClient*, OV2640&) at .pio/libdeps/esp32cam_goouuu/Micro-RTSP/src/OV2640Streamer.cpp:7
  #2  0x42014f9f in rtsp_server::rtsp_client::rtsp_client(WiFiClient const&, OV2640&) at lib/rtsp_server/rtsp_server.cpp:26
  #3  0x420150ef in rtsp_server::client_handler(void*) at lib/rtsp_server/rtsp_server.cpp:36
  #4  0x42014d49 in void Timer<16u, &millis, void*>::tick<void>() at .pio/libdeps/esp32cam_goouuu/arduino-timer/src/arduino-timer.h:134
  #5  0x42014d7c in Timer<16u, &millis, void*>::tick() at .pio/libdeps/esp32cam_goouuu/arduino-timer/src/arduino-timer.h:121
      (inlined by) rtsp_server::doLoop() at lib/rtsp_server/rtsp_server.cpp:20
  #6  0x42006792 in loop() at src/main.cpp:410
  #7  0x42017ee1 in loopTask(void*) at /home/wouter/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:50
```

**board configuration**

```json
{
  "build": {
    "arduino": {
      "ldscript": "esp32s3_out.ld",
      "partitions": "default_16MB.csv",
      "memory_type": "qio_opi"
    },
    "core": "esp32",
    "extra_flags": [
      "-D ARDUINO_ESP32S3_DEV",
      "-D CAMERA_CONFIG_LEDC_TIMER=LEDC_TIMER_0",
      "-D CAMERA_CONFIG_LEDC_CHANNEL=LEDC_CHANNEL_0",
      "-D ARDUINO_USB_MODE=1",
      "-D BOARD_HAS_PSRAM",
      "-D ARDUINO_USB_CDC_ON_BOOT=1",
      "-D ARDUINO_RUNNING_CORE=1",
      "-D ARDUINO_EVENT_RUNNING_CORE=1",
      "-D CAMERA_CONFIG_PIN_PWDN=GPIO_NUM_NC",
      "-D CAMERA_CONFIG_PIN_RESET=GPIO_NUM_NC",
      "-D CAMERA_CONFIG_PIN_XCLK=15",
      "-D CAMERA_CONFIG_PIN_SCCB_SDA=4",
      "-D CAMERA_CONFIG_PIN_SCCB_SCL=5",
      "-D CAMERA_CONFIG_PIN_Y9=16",
      "-D CAMERA_CONFIG_PIN_Y8=17",
      "-D CAMERA_CONFIG_PIN_Y7=18",
      "-D CAMERA_CONFIG_PIN_Y6=12",
      "-D CAMERA_CONFIG_PIN_Y5=10",
      "-D CAMERA_CONFIG_PIN_Y4=8",
      "-D CAMERA_CONFIG_PIN_Y3=9",
      "-D CAMERA_CONFIG_PIN_Y2=11",
      "-D CAMERA_CONFIG_PIN_VSYNC=6",
      "-D CAMERA_CONFIG_PIN_HREF=7",
      "-D CAMERA_CONFIG_PIN_PCLK=13",
      "-D CAMERA_CONFIG_CLK_FREQ_HZ=16000000",
      "-D CAMERA_CONFIG_FB_COUNT=2",
      "-D CAMERA_CONFIG_FB_LOCATION=CAMERA_FB_IN_PSRAM",
      "-D SCCB_I2C_PORT=I2C_NUM_0"
    ],
    "f_cpu": "240000000L",
    "f_flash": "80000000L",
    "flash_mode": "qio",
    "hwids": [
      [
        "0x303A",
        "0x1001"
      ]
    ],
    "mcu": "esp32s3",
    "variant": "esp32s3"
  },
  "connectivity": [
    "bluetooth",
    "wifi"
  ],
  "debug": {
    "default_tool": "esp-builtin",
    "onboard_tools": [
      "esp-builtin"
    ],
    "openocd_target": "esp32s3.cfg"
  },
  "frameworks": [
    "arduino",
    "espidf"
  ],
  "name": "ESP32_CAM GOOUUU",
  "upload": {
    "flash_size": "16MB",
    "maximum_ram_size": 327680,
    "maximum_size": 8388608,
    "require_upload_port": true,
    "speed": 921600
  },
  "url": "",
  "vendor": "GOOUUU"
} 
```

**Comment by rzeldent** [comment]
Looks like a pointer issue. Is the OV2640 instance initialized/present?

**Comment by 33560303** [comment]
> Looks like a pointer issue. Is the OV2640 instance initialized/present?

I think so because it says so on the HTML page.

I already thought it was a pointer issue but I cannot find the actual problem. Maybe I should buy a debugger to run trough the code because I do not have one yet.

In the meantime, do you have any idea if I can confirm/investigate the issue without a debugger?

**Comment by 33560303** [comment]
I have bought myself a debugger and figured it out. It turns out that the OV2640 module was broken. Replacing it solved the issue.

**Comment by 33560303** [comment]
I have bought myself a debugger and solved the issue. It turns out there was a hardware issue with the camera module. Replacing it solved the issue.

**Comment by rzeldent** [comment]
Wow.. nice job!
